#!/bin/bash

# Scenario test: Verifies persistence when codex=true and remoteUser=vscode.
# Corresponds to the "default" scenario in scenarios.json.
#
# How to run:
#   devcontainer features test \
#     --features persistence \
#     --skip-autogenerated \
#     --base-image mcr.microsoft.com/devcontainers/base:ubuntu \
#     /path/to/this/repo
#
# Reference: https://github.com/devcontainers/cli/blob/main/docs/features/test.md

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib. Syntax is...
# check <LABEL> <cmd> [args...]
check "runs as vscode" bash -c "[ \"$(id -un)\" = \"vscode\" ]"
check "codex symlink exists" bash -c "[ -L /home/vscode/.codex ]"
check "codex symlink target" bash -c "[ \"$(readlink /home/vscode/.codex)\" = \"/usr/local/share/persistence/codex\" ]"

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults